name: Update Language Statistics

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente todos los días
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StefVucko/github-language-stats@v1.2.0
        with:
          STATS_TOKEN: ${{ secrets.STATS_TOKEN }}
